### ISSUE TITLE
Remote audio loss after interruption on iOS Safari

### ISSUE THREAD

**Issue by syerrapragada** [twilio/twilio-video.js#1232]
This ticket describes a known remote audio loss issue in the iOS Safari browser when audio is interrupted by other apps.

**Note:** 
- The issue is not a Twilio SDK bug, but an iOS Safari browser issue.

### iOS Safari Participant cannot hear Remote Participants
The issue may happen in any of the following scenarios. In all the below scenarios, A is iOS Safari, B is Desktop Chrome.

**1. Siri scenario**
- A opens Safari and refreshes the page
- B creates room and joins with audio/video
- A joins the same room with audio/video
- Both check if they hear and see each other
- A moves Safari to the background by swiping up and now is on a home screen
- A triggers Siri by long-press the right side button
- A says something to Siri
- A swipe up to close Siri windows
- A press the Safari icon to navigate back to Safari

**2. Messenger scenario**
- A opens Safari and refreshes the page
- B creates room and joins with audio/video
- A joins the same room with audio/video
- Both check if they hear and see each other
- A moves Safari to the background by swiping up and now is on a home screen
- A open Messenger app and make a video call to another user (Not necessary to answer the call)
- A set the Messenger to the background by swiping up and now is on a home screen
- A press the Safari icon to navigate back to Safari

**3. Youtube scenario**
- A opens Safari and refreshes the page
- B creates room and joins with audio/video
- A joins the same room with audio/video
- Both check if they hear and see each other
- A moves Safari to the background by swiping up and now is on a home screen
- A open Youtube app and watches video for 10 sec
- A set the Youtube to the background by swiping up and now is on a home screen
- A press the Safari icon to navigate back to Safari

**Affected iOS Versions** 
- iOS 14.1
- iOS 14.0.1
- iOS 14
- iOS 13.7

JS SDK Engineering Team is currently investigating the issue.

Please ensure that you are on JS SDK 2.7.1 or greater as there other Safari bugs that are also audio related that were resolved in that release.

**Comment by markbrouch** [comment]
Thank you for investigating this issue. I believe it is related to https://github.com/twilio/twilio-video.js/issues/1206 as well (feel free to close that issue if so).

**Comment by maximromanyuk** [comment]
Waiting for this issue to be resolved

**Comment by mattpanico** [comment]
Any chance this is fixed by #1235? That PR claims to fix #1206.

**Comment by manjeshbhargav** [comment]
@markbrouch @maximromanyuk We have released [twilio-video.js@2.7.3](https://github.com/twilio/twilio-video.js/releases/2.7.3) which fixes these issues.

**Comment by manjeshbhargav** [comment]
@mattpanico 

> Any chance this is fixed by #1235? That PR claims to fix #1206.

Yes, it does. We just released [2.7.3](https://github.com/twilio/twilio-video.js/releases/2.7.3) and [2.8.0-beta.2](https://github.com/twilio/twilio-video.js/releases/2.8.0-beta.2) with the fix for this issue.

**Comment by ggoldens** [comment]
Is there any workaround for these remote audio issues?

**Comment by ggoldens** [comment]
Hi, is there any update on this issues? Have you filed a bug in Apple already?

**Comment by marymhart** [comment]
@manjeshbhargav It appears this is still broken with 2.7.3 & iOS 14.2 & 14.3 beta in the following scenario. A is  Desktop Chrome, B is iOS safari. In 2.7.2 the audio cuts out at point 5 but the video does not freeze. 

1. A creates room
2. B Joins room on safari iOS with audio/video
3. Both check if they hear and see each other
4. B receives phone call & declines call from the notification
5. B's video freezes for both users
