### ISSUE TITLE
WARN RemoteParticipant#trackAdded has been deprecated

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#395]
Hello,

Since we have upgraded to v1.13.1 we have started to see hundreds of the following logged on Sentry. We are not using any deprecated APIs. Are they used internally? If yes, are there any plans to fix them before v2 release?

Thanks

```
2018-08-13` 22:18:07.189Z | WARN in [RemoteParticipant #2: PAf589cadc0a2a13f0a883954deedf5daf]:
RemoteParticipant#trackAdded has been deprecated and scheduled for removal in twilio-video.js@2.0.0. Use RemoteParticipant#trackSubscribed instead.
```

**Comment by manjeshbhargav** [comment]
@katranci ,

Thanks for bringing this to our notice. After some digging around, we noticed that we internally listen to the `RemoteParticipant`'s listeners to re-emit those events on the `Room`.

We apologize for the inconvenience that this has caused you. We have scheduled the work to fix this, and we are planning to release the fix approximately in the middle of next week. We will reach out to you once the fix is available.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by markandrus** [comment]
@gjdownes,

Yes, you'll still be able to listen to "trackSubscribed" on the Room. "trackSubscribed" replaces "trackAdded".

> I find this particularly handy as all/most of my listeners can be handled in one place.

Thanks for the feedback! This helps as we continue to add APIs :-)

Best,
Mark

**Comment by markandrus** [comment]
@katranci and to anyone else affected by this bug,

We're releasing 1.14.0 today which will solve it.

Best,
Mark

**Comment by markandrus** [comment]
1.14.0 is released.

**Comment by smkrn110** [comment]
The issue still remains there do I have to upgrade anything else? I tested with both 1.14.0 and 1.14.1

**Comment by smkrn110** [comment]
@manjeshbhargav 

We are still facing this issue, with version 1.14.1, using both `trackAdded` and `trackSubscribed`. 

With Chrome all is working great, but with Firefox we are facing this issue. I could provide details with new issue, if require.

Thanks

**Comment by manjeshbhargav** [comment]
@smkrn110 ,

It looks like what you are describing is not related to this issue, which is about deprecation warnings. Please open a new issue with the details of your observations.

Thanks,

Manjesh Malavalli
JSDK Team
