### ISSUE TITLE
CRITICAL - Join meeting not working on Chrome

### ISSUE THREAD

**Issue by mjamal-tiu** [twilio/twilio-video.js#576]
I need your help in Twilio Programmable Video feature. We have implemented the Programmable Video feature in out website and it was working fine until last week and suddenly the Connect to Room (Join button) stops working and when I have checked the browser's console I got the below error from the twilio-video.js file.

"WebSocket connection to 'wss://sdkgw.us1.twilio.com/v1/VideoEvents' failed: WebSocket is closed before the connection is established."

Can anyone please provide your suggestion or let me know what and how can I resolve this or it is at Twilio JS issue which we are using from CDN?

Twilio-video.js is below which we used.
https://media.twiliocdn.com/sdk/js/video/releases/1.11.1/twilio-video.js

**Comment by manjeshbhargav** [comment]
Hi @mjamal-tiu ,

Thanks for writing in with your issue. In December 2018, we published a [customer advisory](https://support.twilio.com/hc/en-us/articles/360012782494-Breaking-Changes-in-Twilio-Video-JavaScript-SDKs-December-2018-) where we mentioned that Chrome is making some breaking changes starting from Chrome 72, and we recommended upgrading to the latest versions of the SDK (twilio-video.js@1.15.2 for your use-case) in order for your application to continue working on newer versions of Chrome. You can also find this advisory in this repository's [home page](https://github.com/twilio/twilio-video.js). Please let me know if upgrading solves your problem.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by mjamal-tiu** [comment]
Hello Manjesh,

Yes, as you mentioned in your reply, the issue is due to the old version of twilio-video.js was used in our application and which was resulting issue at Google Chrome. 
Now I am using the twilio-video.js@1.14.1 version and it starts working as expected. Below is the URL of details.
https://support.twilio.com/hc/en-us/articles/360012782494-Breaking-Changes-in-Twilio-Video-JavaScript-SDKs-December-2018-

Thanks for your advice.

**Comment by manjeshbhargav** [comment]
Hi @mjamal-tiu ,

I'm really glad to hear that your issue got resolved. I will close this issue now.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by mjamal-tiu** [comment]
Hi Manjesh,

From using the latest version of the twilio-video.js (I am now using URL https://media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js), now I can join the room but again I am now facing one new issue and which is the "Share screen" feature which I am using in my website. I am using Chrome Extension for screen sharing and extension we have released.

I am getting below error browser console while clicking on the "Share screen" button and when clicking on "Add to Chrome" link.
------------------------------------
2MzY2:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
quickstart_ex.js:57 Uncaught (in promise) Error: Could not get stream
    at quickstart_ex.js:57
(anonymous) @ quickstart_ex.js:57
Promise.then (async)
document.getElementById.onclick @ quickstart_ex.js:152
MzY2:166 Uncaught TypeError: Cannot read property 'install' of undefined
    at HTMLAnchorElement.onclick (MzY2:166)
------------------------------------

When I am using 1.11.1 version, the join meeting and screen sharing both were working fine.

Please provide your inputs.

**Comment by manjeshbhargav** [comment]
Hi @mjamal-tiu ,

Chrome 72 onwards will no longer expose the `webstore` APIs on the global namespace `chrome`. That is why you are getting the error message "cannot read property 'install' of undefined". So you would have to navigate to the extension's webstore url for the extension to be installed.

Having said that, Chrome 72 supports `navigator.mediaDevices.getDisplayMedia()` which is a way to get the screen share media without an extension. So, you can migrate to this API and get rid of the screen share extension altogether for newer versions of Chrome.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by satdevops88** [comment]
Hello, @mjamal-tiu 
How are you?
I am also getting same error when trying connect to room.
"Unable to connect to Room: Signaling connection error"
Can you help me this?

**Comment by mjamal-tiu** [comment]
Hello @satdevops88 ,

I have updated my inline install event from "chrome.webstore.install()" to replace with my Chrome extension store detail page URL for installing the extension and after installing an extension at the Chrome extension store my websites functionality works.
For more information please see the below URL which is provided by one of Twilio development team member.
https://developer.chrome.com/extensions/inline_faq

Hope that will help you.

**Comment by satdevops88** [comment]
Hello @manjeshbhargav 
Nice to meet you.
I am still getting TwilioError: Singaling connection error.
![image](https://user-images.githubusercontent.com/46093186/54838595-96156e80-4cfb-11e9-8f1f-11456ef317cd.png)

Please help me.
Thanks.

**Comment by innerverse** [comment]
Hi @satdevops88 ,

Thanks for writing in, and I'm sorry you're running into trouble getting set up!  Can you please open a new issue and fill out the template completely?  It will helps us troubleshoot this further.

Thank you,
Seth
Video Team

**Comment by akvaliya** [comment]
Hello @satdevops88 I am getting the same error. Did you by any chance found any solution?

I am getting this error when i use twilio-video in lazyloaded component. FYI.

**Comment by ayafaheem** [comment]
I am getting same issue 
> Ready and connected as 'test'...

> Joining room 'test'...

> Could not connect to Twilio: Signaling connection disconnected

**Comment by anna-vasilko** [comment]
@ayafaheem  The issue may happen if you use an old SDK version and/or an old version of Chrome. Updating SDK version fixed it for the initial reporter. If updating SDK/browser does not fix it for you, please provide more info (what sdk/browser version you use, either you use any extensions, specifics of you environment etc). Code and log snippets will help a lot.

**Comment by ayafaheem** [comment]
Chrome Version 79.0.3945.88 (Official Build) (64-bit) 
I used this example 
https://github.com/philnash/screen-capture

**Comment by anna-vasilko** [comment]
@ayafaheem Thanks. Can you check what SDK version is actually used by your app? You should be able to check in Chrome console by typing `Twilio.Video.version`. 
Latest stable v1 version of twilio-video.js is 1.20.0. If your version is bellow that, please upgrade.
Meantime we'll try to repro your issue with this screen-capture example.

**Comment by ayafaheem** [comment]
video-call@1.0.0 build
checked attached image 
http://prntscr.com/qem6id

**Comment by ayafaheem** [comment]
Dear @anna-vasilko  I did update it's work to me now 
+ watchify@3.11.1
+ concurrently@3.6.1
+ twilio@3.39.1
+ express@4.17.1
+ twilio-video@1.20.0

But when I click share screen button this issue appear to me 

Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
index.js:36749 Uncaught (in promise) Error: Could not get stream

**Comment by ayafaheem** [comment]
Dear I need to  know where this path /token   $.getJSON('/token?identity=' 
because I get this issue  when I try to run example without using npm start port 3000

<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /token was not found on this server.</p>

**Comment by manjeshbhargav** [comment]
@ayafaheem ,

Are you using the [Video JS QuickStart]()? If so, then the `/token` endpoint is available on the same server. So, you have to be running the server to access the endpoint.

Anyway, this looks like a different issue than the one being discussed here. Can you open a new issue and fill out the issue template with more details? It will greatly help us in helping you navigate through your problem.

Thanks,

Manjesh

**Comment by ayafaheem** [comment]
yes , I'm using  the Video JS QuickStart , there is another way can i use to integrate twilio share screen without need to run using node js (npm start port 3000)

**Comment by ajru** [comment]
Hi Team 
          Am using Twilio for video conferences, am using //media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js to connect with room 
 Twilio.Video.createLocalTracks({
            audio: true,
            video: {
                width: 300
            }
        }).then(function(localTracks) {
            console.log("$accessToken ", '<?php echo  $accessToken ?>', 'roomname',' {{ $roomName }}','localTracks',localTracks)
            return Twilio.Video.connect('<?php echo  $accessToken ?>', {
                name: '<?php echo  $roomName ?>',
                tracks: localTracks,
                video: {
                    width: 300
                }
            }).catch(error => {
                console.log("error", error)
            });
        }).then(function(room) {
            console.log(' Room: ', room);
            // console.log('Successfully joined a Room: ', room);

            room.participants.forEach(participantConnected);

            var previewContainer = document.getElementById(room.localParticipant.sid);
            if (!previewContainer || !previewContainer.querySelector('video')) {
                participantConnected(room.localParticipant);
            }

            room.on('participantConnected', function(participant) {
                console.log("Joining: '", participant.identity, "'");
                participantConnected(participant);
            });

            room.on('participantDisconnected', function(participant) {
                console.log("Disconnected: '",
                    participant.identity, "'");
                participantDisconnected(participant);
            });
        })

with this code. but am facing one error in the js console while testing it out on local

![image](https://user-images.githubusercontent.com/12871608/159439618-108e8cbc-05b3-4ec5-916f-68ae1f0d465f.png)


can you please help me out with this. ?
Thanks

**Comment by Lambertn33** [comment]
@ajru  hello 
were you able to find to solution please?? i am getting the same error now
